version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgres" 
      POSTGRES_USER: "postgres" 
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
    #healthcheck:

volumes:
  pgdata:
